
### 1 новый пользователь
POST http://localhost:8089/api/users
Content-Type: application/json

{
  "email": "testtt1111111111111111@mail.com",
  "phone": "71236666666",
  "name": "тест!!11"
}

> {%
    client.global.set("userId", response.body.id);
%}


### 2 новый заказ
POST http://localhost:8089/api/orders
Content-Type: application/json

{
  "userId": "270c44e5-07cf-41f4-8d43-22d0cf6da9fd",
  "senderAddress": "Москва, ул. Пушкина, д. 1",
  "recipientAddress": "MARS, ул. Лермонтова, д. 10",
  "weight": 2.5
}
> {%
    client.global.set("orderId", response.body.id);
%}

### 3 удаление

DELETE http://localhost:8089/api/orders/{{orderId}}

### расчёт стоимости
GET http://localhost:8089/api/orders/calculate?from=Moscow&to=Minsk&weight=2.0
Accept: application/json
