global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "microservices_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [
          "couriers:8080",
          "audit-service:8082",
          "notification-service:8083",
          "pricing-service:8084",
          "statistics-service:8081"
        ]