type User {
    id: ID!
    email: String
    phone: String
    name: String
}

type Courier {
    id: ID!
    name: String
    phone: String
    deliveryMethod: String
    status: String
    latitude: Float
    longitude: Float
}

type Order {
    id: ID!
    user: User
    courier: Courier
    senderAddress: String
    recipientAddress: String
    status: String
    price: Float
    createdAt: String
    updatedAt: String
}

type CourierPage {
    content: [Courier]
    number: Int
    size: Int
    totalElements: Int
    totalPages: Int
}


type Query {
    userById(id: ID!): User
    orderById(id: ID!): Order
    courierById(id: ID!): Courier
    allCouriers(page: Int = 0, size: Int = 10): CourierPage
}


input CreateUserInput {
    email: String!
    password: String!
    phone: String!
    name: String!
}

input CreateCourierInput {
    email: String!
    password: String!
    phone: String!
    name: String!
    deliveryMethod: String!
}

input CreateOrderInput {
    senderAddress: String!
    recipientAddress: String!
    weight: Float!
}

input UpdateCourierStatusInput {
    status: String!
}

input UpdateCourierLocationInput {
    latitude: Float!
    longitude: Float!
}


type Mutation {
    registerUser(input: CreateUserInput!): User
    registerCourier(input: CreateCourierInput!): Courier
    createOrder(input: CreateOrderInput!): Order
    updateCourierStatus(id: ID!, input: UpdateCourierStatusInput!): Courier
    updateCourierLocation(id: ID!, input: UpdateCourierLocationInput!): Courier
    acceptOrder(orderId: ID!): Boolean
    declineOrder(orderId: ID!): Boolean
    changeDeliveryStatus(orderId: ID!, newStatus: String!): Boolean
}